/**
 * Ví dụ Decision Tree theo từng ứng dụng (dùng ở example.html).
 */
window.APP_EXAMPLES = {
  medical: {
    id: "medical",
    icon: "🏥",
    title: "Chẩn đoán y tế",
    blurb: "Dự đoán có cần khám thêm hay không dựa trên triệu chứng.",
    labelKey: "result",
    labelName: "Kết luận",
    features: [
      { key: "fever", label: "Sốt?" },
      { key: "cough", label: "Ho?" },
      { key: "fatigue", label: "Mệt?" },
    ],
    columns: [
      { key: "name", label: "Bệnh nhân" },
      { key: "fever", label: "Sốt" },
      { key: "cough", label: "Ho" },
      { key: "fatigue", label: "Mệt" },
      { key: "result", label: "Khám thêm?" },
    ],
    rows: [
      { name: "BN1", fever: "Có", cough: "Có", fatigue: "Có", result: "Có" },
      { name: "BN2", fever: "Có", cough: "Không", fatigue: "Có", result: "Có" },
      { name: "BN3", fever: "Không", cough: "Có", fatigue: "Không", result: "Không" },
      { name: "BN4", fever: "Không", cough: "Không", fatigue: "Không", result: "Không" },
      { name: "BN5", fever: "Có", cough: "Có", fatigue: "Không", result: "Có" },
      { name: "BN6", fever: "Không", cough: "Có", fatigue: "Có", result: "Có" },
      { name: "BN7", fever: "Không", cough: "Không", fatigue: "Có", result: "Không" },
      { name: "BN8", fever: "Có", cough: "Không", fatigue: "Không", result: "Có" },
    ],
  },

  fraud: {
    id: "fraud",
    icon: "💳",
    title: "Phát hiện gian lận",
    blurb: "Giao dịch bất thường → nghi ngờ gian lận hay hợp lệ.",
    labelKey: "result",
    labelName: "Gian lận?",
    features: [
      { key: "amount", label: "Số tiền?" },
      { key: "abroad", label: "Nước ngoài?" },
      { key: "night", label: "Ban đêm?" },
    ],
    columns: [
      { key: "name", label: "GD" },
      { key: "amount", label: "Số tiền" },
      { key: "abroad", label: "NN" },
      { key: "night", label: "Đêm" },
      { key: "result", label: "Gian lận?" },
    ],
    rows: [
      { name: "GD1", amount: "Cao", abroad: "Có", night: "Có", result: "Có" },
      { name: "GD2", amount: "Cao", abroad: "Có", night: "Không", result: "Có" },
      { name: "GD3", amount: "Thấp", abroad: "Không", night: "Không", result: "Không" },
      { name: "GD4", amount: "Trung bình", abroad: "Không", night: "Có", result: "Không" },
      { name: "GD5", amount: "Cao", abroad: "Không", night: "Có", result: "Có" },
      { name: "GD6", amount: "Thấp", abroad: "Có", night: "Có", result: "Có" },
      { name: "GD7", amount: "Trung bình", abroad: "Không", night: "Không", result: "Không" },
      { name: "GD8", amount: "Thấp", abroad: "Không", night: "Có", result: "Không" },
    ],
  },

  credit: {
    id: "credit",
    icon: "🏦",
    title: "Duyệt tín dụng",
    blurb: "Ngân hàng quyết định duyệt hay từ chối khoản vay.",
    labelKey: "result",
    labelName: "Duyệt?",
    features: [
      { key: "income", label: "Thu nhập?" },
      { key: "debt", label: "Nợ cũ?" },
      { key: "job", label: "Ổn định?" },
    ],
    columns: [
      { key: "name", label: "KH" },
      { key: "income", label: "Thu nhập" },
      { key: "debt", label: "Nợ cũ" },
      { key: "job", label: "Công việc" },
      { key: "result", label: "Duyệt?" },
    ],
    rows: [
      { name: "KH1", income: "Cao", debt: "Thấp", job: "Ổn định", result: "Có" },
      { name: "KH2", income: "Cao", debt: "Cao", job: "Ổn định", result: "Không" },
      { name: "KH3", income: "Thấp", debt: "Thấp", job: "Ổn định", result: "Không" },
      { name: "KH4", income: "Trung bình", debt: "Thấp", job: "Ổn định", result: "Có" },
      { name: "KH5", income: "Cao", debt: "Thấp", job: "Tạm thời", result: "Có" },
      { name: "KH6", income: "Thấp", debt: "Cao", job: "Tạm thời", result: "Không" },
      { name: "KH7", income: "Trung bình", debt: "Cao", job: "Ổn định", result: "Không" },
      { name: "KH8", income: "Trung bình", debt: "Thấp", job: "Tạm thời", result: "Có" },
    ],
  },

  shopping: {
    id: "shopping",
    icon: "🛒",
    title: "Gợi ý mua hàng",
    blurb: "Khách có khả năng mua sản phẩm được gợi ý hay không.",
    labelKey: "result",
    labelName: "Mua?",
    features: [
      { key: "viewed", label: "Đã xem?" },
      { key: "cart", label: "Trong giỏ?" },
      { key: "promo", label: "Có khuyến mãi?" },
    ],
    columns: [
      { key: "name", label: "KH" },
      { key: "viewed", label: "Đã xem" },
      { key: "cart", label: "Giỏ hàng" },
      { key: "promo", label: "KM" },
      { key: "result", label: "Mua?" },
    ],
    rows: [
      { name: "KH1", viewed: "Có", cart: "Có", promo: "Có", result: "Có" },
      { name: "KH2", viewed: "Có", cart: "Có", promo: "Không", result: "Có" },
      { name: "KH3", viewed: "Có", cart: "Không", promo: "Có", result: "Có" },
      { name: "KH4", viewed: "Không", cart: "Không", promo: "Có", result: "Không" },
      { name: "KH5", viewed: "Không", cart: "Không", promo: "Không", result: "Không" },
      { name: "KH6", viewed: "Có", cart: "Không", promo: "Không", result: "Không" },
      { name: "KH7", viewed: "Không", cart: "Có", promo: "Có", result: "Có" },
      { name: "KH8", viewed: "Không", cart: "Có", promo: "Không", result: "Không" },
    ],
  },

  quality: {
    id: "quality",
    icon: "🏭",
    title: "Kiểm soát chất lượng",
    blurb: "Sản phẩm đạt chuẩn hay cần loại bỏ trên dây chuyền.",
    labelKey: "result",
    labelName: "Đạt?",
    features: [
      { key: "size", label: "Kích thước?" },
      { key: "surface", label: "Bề mặt?" },
      { key: "weight", label: "Khối lượng?" },
    ],
    columns: [
      { key: "name", label: "SP" },
      { key: "size", label: "Size" },
      { key: "surface", label: "Bề mặt" },
      { key: "weight", label: "KL" },
      { key: "result", label: "Đạt?" },
    ],
    rows: [
      { name: "SP1", size: "Đúng", surface: "Trơn", weight: "Đạt", result: "Có" },
      { name: "SP2", size: "Đúng", surface: "Trơn", weight: "Lệch", result: "Không" },
      { name: "SP3", size: "Sai", surface: "Trơn", weight: "Đạt", result: "Không" },
      { name: "SP4", size: "Đúng", surface: "Trầy", weight: "Đạt", result: "Không" },
      { name: "SP5", size: "Đúng", surface: "Trầy", weight: "Lệch", result: "Không" },
      { name: "SP6", size: "Sai", surface: "Trầy", weight: "Lệch", result: "Không" },
      { name: "SP7", size: "Đúng", surface: "Trơn", weight: "Đạt", result: "Có" },
      { name: "SP8", size: "Sai", surface: "Trơn", weight: "Lệch", result: "Không" },
    ],
  },

  spam: {
    id: "spam",
    icon: "📧",
    title: "Lọc spam",
    blurb: "Email là spam hay thư hợp lệ dựa trên dấu hiệu đơn giản.",
    labelKey: "result",
    labelName: "Spam?",
    features: [
      { key: "link", label: "Có link lạ?" },
      { key: "urgent", label: "Khẩn cấp?" },
      { key: "known", label: "Người gửi quen?" },
    ],
    columns: [
      { key: "name", label: "Mail" },
      { key: "link", label: "Link lạ" },
      { key: "urgent", label: "Khẩn" },
      { key: "known", label: "Quen" },
      { key: "result", label: "Spam?" },
    ],
    rows: [
      { name: "M1", link: "Có", urgent: "Có", known: "Không", result: "Có" },
      { name: "M2", link: "Có", urgent: "Không", known: "Không", result: "Có" },
      { name: "M3", link: "Không", urgent: "Không", known: "Có", result: "Không" },
      { name: "M4", link: "Không", urgent: "Có", known: "Có", result: "Không" },
      { name: "M5", link: "Có", urgent: "Có", known: "Có", result: "Có" },
      { name: "M6", link: "Không", urgent: "Có", known: "Không", result: "Có" },
      { name: "M7", link: "Không", urgent: "Không", known: "Không", result: "Không" },
      { name: "M8", link: "Có", urgent: "Không", known: "Có", result: "Không" },
    ],
  },
};
